 -- THIS IS USE FOR CLEAR ALL THE DUPLICATE VALUE
 
SELECT DISTINCT CITY FROM STUDENT;
 
 -- CLUSES MEAN CONDITION
 -- WHERE CLAUSE MEAN TO DEFINE SOME CONDITION 
 
SELECT * FROM STUDENT WHERE MARKS > 80;
SELECT * FROM STUDENT WHERE MARKS > 80 AND CITY  = 'MUMBAI';

-- AND OPERATOR
SELECT * FROM STUDENT WHERE MARKS + 10 > 100 And city = 'MUMBAI';

-- OR OPERATOR
SELECT * FROM STUDENT WHERE MARKS + 10 > 100 OR city = 'MUMBAI';

-- BETWEEN OPERATOR
SELECT * FROM STUDENT WHERE MARKS BETWEEN 80 AND  90;

-- IN OPERATOR
SELECT * FROM STUDENT WHERE city IN ('MUMBAI', 'DELHI');

-- NOT IN OPEARTOR
SELECT * FROM STUDENT WHERE city NOT IN ('MUMBAI', 'DELHI');


-- LIMITE IS IT SELF IS CLAUSE
SELECT * FROM STUDENT WHERE CITY = 'DELHI';
SELECT * FROM STUDENT WHERE CITY = 'DELHI' LIMIT 2;

-- ORDER BY CLAUSE 
SELECT * FROM STUDENT ORDER BY MARKS DESC LIMIT 3	;
SELECT * FROM STUDENT ORDER BY MARKS ASC LIMIT 3;
SELECT * FROM STUDENT ORDER BY CITY ASC;

-- AGGREGATION FUNCTION
-- COUNT()
-- MAX()
-- MIN()
-- SUM()
-- AVG()

SELECT COUNT(NAME) FROM STUDENT;
SELECT MAX(MARKS) FROM STUDENT;
SELECT MIN(MARKS) FROM STUDENT;
SELECT SUM(MARKS) FROM STUDENT;
SELECT AVG(MARKS) FROM STUDENT; 


-- GROUP BY CLAUSE
SELECT CITY, AVG(MARKS) FROM STUDENT GROUP BY CITY;
SELECT CITY, AVG(MARKS) FROM STUDENT GROUP BY CITY ORDER BY AVG(MARKS);

-- HAVING CLUSE ALSO DEFINE CONDITION BUT IT APPLY ON GROUP WHERE WHERE CLAUSE APPLY CONDITION ON NORMAL CONDITION
SELECT CITY , COUNT(MARKS) FROM STUDENT GROUP BY CITY HAVING MAX(MARKS) > 90;

-- UPDATE QUERY
UPDATE STUDENT SET GREAD = 'O' WHERE GREAD = 'A';
SELECT GREAD, COUNT(ROLLNO) FROM STUDENT GROUP BY GREAD;