USE PRACTICE;
-- GIVE THE TOTAL PAYMENT ACCODING  TO EACH PAYMENT METHOD
SELECT MODE, COUNT(CUSTOMER_ID) FROM PAYMENT GROUP BY MODE;
UPDATE PAYMENT SET MODE = 'NETBANKING' WHERE CUSTOMER_ID = 104;
SELECT * FROM PAYMENT