USE PRACTICE ;
 DROP TABLE PATMENT; 
 
 create table PAYMENT (
 CUSTOMER_ID INT PRIMARY KEY,
 CUSTOMER VARCHAR(50),
 MODE VARCHAR(50),
 CITY VARCHAR(50)
);


INSERT INTO PAYMENT (CUSTOMER_ID, CUSTOMER, MODE, CITY) VALUES
(101, 'OLIVIA BARRETT','NETBANKING','PORTLAND'),
(102, 'ETHAN SINCLAIR', 'CREDIT CARD', 'MAIMI'),
(103, 	'MAYA HERNANDZ', 'CRADIT CARD"', 'SEATTLE'),
(104, 'LIAM DONOVAN', 'NETNANKING', 'DENVER'),
(105, 'SOPHIA NGUYEN', 'CRADIT CARD', 'NEW ORLEANS'),
(106, 'CALEG FOSTER', 'DABIT CARD', 'MINNEAPOLIS'),
(107, 'AVA PATAL', 'DEBIT CARD', 'PHEONIX'),
(108, 'LUCAS CARTER', 'NETBANKING' ,'BOSTON'),
(109, 'ISABALLA MARTINEZ' ,'NETBANKING', 'NASHVILLE'),
(110, 'JACKSON BROOKS', 'CRADIT CARD', 'BOSTON');